language: node_js

before_install:
- $(! $TRAVIS_SECURE_ENV_VARS) || openssl aes-256-cbc -K $encrypted_e3a4f5cf648a_key -iv $encrypted_e3a4f5cf648a_iv
  -in service-account.json.enc -out service-account.json -d

install: ./git-lfs.sh
script: true

deploy:
  provider: gae
  project: coduno
  verbosity: debug
  skip_cleanup: true
