service: default
runtime: python27
api_version: 1
threadsafe: yes

handlers:
  - url: /assets
    static_dir: assets
    secure: always
    http_headers:
      strict-transport-security: max-age=15552000

  - url: /register
    static_files: static/register/index.html
    upload: static/register/index.html
    http_headers:
      strict-transport-security: max-age=15552000

  - url: /
    static_files: static/index.html
    upload: static/index.html
    secure: always
    http_headers:
      strict-transport-security: max-age=15552000

  - url: /
    static_dir: static
    secure: always
    http_headers:
      strict-transport-security: max-age=15552000

