name: coduno
description: Frontend for www.cod.uno
authors:
  - Lorenz Leutgeb <lorenz.leutgeb@cod.uno>
transformers:
  - $dart2js:
      minify: true
      checked: true
      verbose: true
#     analyzeAll: true
#     enableDiagnosticColors: true
      csp: true
#     dumpInfo: true
#     $include: "web/hello.dart"
  - polymer
dependencies:
  browser: ">=0.10.0 <0.11.0"
  polymer: ">=0.15.1 <0.16.0"
  core_elements: ">=0.5.0 <0.6.0"
  paper_elements: ">=0.6.0 <0.7.0"
